tempbuys/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path("signin", views.signin, name="signin"),
    path("signup",views.signup,name="signup"),
    path('logout', views.logout, name='logout'),
    path("profile",views.profile,name="profile"),
    path("profile_password",views.profile_password,name="profile_password"),
    path("bill",views.bill,name="bill"),
    path("security",views.security,name="security"),

    # path('forget',views.forgot_password,name='forget'),
]

tempbuys/loginregister/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path("signin", views.signin, name="signin"),
    path("signup", views.signup, name="signup"),
    path('logout', views.logout, name='logout'),
    path("bill", views.bill, name="bill"),
    path("forgot_password",views.forgot_password,name='forgot_password'),
    path("is_otp_expired",views.is_otp_expired,name="is_otp_expired"),
    path("handle_otp",views.handle_otp,name="handle_otp"),
    path("password_update",views.password_update,name="password_update"),
    path("profile_page", views.profile_page, name="profile_page"),
    path("profile_password", views.profile_password, name="profile_password"),
    path("profile_forgot_password", views.profile_forgot_password, name='profile_forgot_password'),
    path("profile_handle_otp", views.profile_handle_otp, name="profile_handle_otp"),
    path("profile_password_update", views.profile_password_update, name="profile_password_update"),
    path('verify_email/<str:token>/', views.verify_email, name='verify_email'),


]

tempbuys/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('',views.home,name='home'),
    path("temp_view/<int:template_card_id>/",views.temp_view,name="temp_view"),
    path("morenormal",views.moreNormal,name="morenormal"),
    path("morepremium",views.morePremium,name="morepremium"),
    path('pay/<int:template_id>/',views.pay,name='pay'),
    path("coupen/<int:id>/",views.coupen,name='coupen'),
    path("delcoupen/<int:template_id>/",views.delcoupen,name='delcoupen'),
    path("checkout/<int:id>/",views.checkout,name='checkout'),
    path("success/",views.success,name="success"),
    path('failed/',views.paymentfailed,name="failed"),
    path('somethingwentwrong/',views.somethingwentwrong,name="somethingwentwrong"),
]

tempbuys/tempbuys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',include('customadmin.urls')),
    path('dfadmin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('loginregister',include('loginregister.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tempbuys/templates/frame.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,700|Roboto:400,900" rel="stylesheet">
     <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
    
    

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

</head>
<body>


<!-- <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mainapp:home' %}"><i class="fa-solid fa-house fa-2xl" style="color: #f6132a;"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#" onclick="webSize()"><i class="fa-solid fa-desktop fa-xl" style="color: #050505;"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" onclick="mobileSize()"><i class="fa-solid fa-mobile-screen fa-xl" style="color: #050505;"></i></a>
        </li>
        <li class="d-flex">
            {% if request.session.is_logged_in %}
          <a href="{% url 'mainapp:pay' template_card.id %}">
            <button class="btn btn-outline-success" type="button">Purchase</button>
          </a>
            {% else %}
            <a href="">
            <button class="btn btn-outline-success" type="button">Login</button>
          </a>
            {% endif %}
        </li>
    </div>
  </div>
</nav> -->

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mainapp:home' %}">
      <i class="fa-solid fa-house fa-2xl" style="color: #f6132a;"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#" onclick="webSize()">
            <i class="fa-solid fa-desktop fa-xl" style="color: #050505;"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" onclick="mobileSize()">
            <i class="fa-solid fa-mobile-screen fa-xl" style="color: #050505;"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto"> <!-- Changed ml-auto to ms-auto (margin-start) -->
        <li class="nav-item">
          {% if request.session.is_logged_in %}
            <a href="{% url 'mainapp:pay' template_card.id %}">
              <button class="btn btn-outline-success" type="button">Purchase</button>
            </a>
          {% else %}
            <a href="{% url 'login:signin' %}">
              <button class="btn btn-outline-success" type="button">Login</button>
            </a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>


<div id="web">
<!--  <div class="embed-responsive embed-responsive-16by9">-->
<!--           <iframe class="embed-responsive-item" src="main.html" style="width:100%;height:600px;" allowfullscreen></iframe>-->
<!--  </div>-->
  <iframe srcdoc="{{content}}" style="width:100%;height:680px;" id="encoder_frame"></iframe>
</div>

<div id="mobile" style="display:none;">
  <div class="container">
    <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="margin-top:20px;">
      <div class="card" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)">
      <div class="col-md-12">
      <iframe srcdoc="{{content}}" style="width:100%;height:500px;" scrolling="auto;"></iframe>
    </div>
        </div>
    </div>
    <div class="col-md-4"></div>
      </div>
  </div>
</div>

<script>
  function webSize(){
    document.getElementById("web").style.display = "block" ;
    document.getElementById("mobile").style.display = "none" ;
  }

  function mobileSize(){
    document.getElementById("web").style.display = "none";
    document.getElementById("mobile").style.display = "block";
  }
</script>
<script>
function loginAlert() {
  alert("Please login first!");
}
</script>
<!--<script type="text/javascript">function loginAlert(){if (confirm("click ok to continue")) window.location = "link.html";}</script>-->
</body>
</html>

tempbuys/templates/morenormal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Gallery</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
         <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="static/mainhtml/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="static/mainhtml/assets/css/main.css" rel="stylesheet">

       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</head>

<body>

<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1><img src="static/mainhtml/assets/img/foxdale/foxdalenavbar.jpg"></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'mainapp:home' %}#home">Home</a></li>
          <li><a href="{% url 'mainapp:home' %}#about">About</a></li>
          <li><a href="{% url 'mainapp:home' %}#premium">Premium Templates</a></li>
          <li><a href="#footer">Contact</a></li>
          <li><a href=""></a></li>
            <form class="d-flex" role="search" method="get" action="{% url 'mainapp:morenormal' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

        </ul>
      </nav><!-- .navbar -->

      <a class="btn-book-a-table" href="{% url 'login:signin' %}">Login</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header>

  <style>
    .menu-item {
      position: relative;
      overflow: hidden;
    }
  
    .menu-im {
      transition: transform 0.3s ease-in-out;
    }
  
    .menu-item:hover .menu-im,
    .menu-item.touch-active .menu-im {
      transform: scale(1.1);
    }
  
    .preview-button {
      position: absolute;
      bottom: 0;
      right: 0;
      margin: 10px;
      background-color: #ce1212;
      color: white;
      padding: 10px 20px;
      text-decoration: none;
      opacity: 0;
      transition: opacity 0.3s ease-in-out;
      pointer-events: none; /* Make the button not respond to mouse events */
    }
  
    .menu-item:hover .preview-button {
      opacity: 1;
    }
  </style>
  
  <script>
    // Add touch event handling using JavaScript
    document.addEventListener("DOMContentLoaded", function () {
      var menuItems = document.querySelectorAll(".menu-item");
  
      menuItems.forEach(function (menuItem) {
        menuItem.addEventListener("touchstart", function () {
          this.classList.add("touch-active");
        });
  
        menuItem.addEventListener("touchend", function () {
          this.classList.remove("touch-active");
        });
      });
    });
  </script>

<div class="container" style="margin-top:150px;">
   <div class="row">
       {% if query %}
       {% for s in search %}
       <!-- <div class="col-md-4">
           <div class="card" style="width:360px;margin:30px;">
               <a href="{% url 'mainapp:temp_view' s.id %}">
               <img src="{{s.temp_img.url}}" class="card-img-top" alt="..." >
                </a>
           </div>
       </div> -->
       <div class="col-lg-4 menu-item" style="margin-bottom:70px;">
        <a href="{% url 'mainapp:temp_view' s.id %}">
          <img src="{{s.temp_img.url}}" class="menu-im img-fluid" alt="" style="width:100%; height:200px; margin-right:20px;">
          <a type="submit" href="{% url 'mainapp:temp_view' s.id %}" class="preview-button btn">
            <i class='fas fa-eye' style="margin-right:7px;"></i>Preview
          </a>
        </a>
      </div>
       {% endfor %}
       {% else %}
       {% for n in normal %}
       <!-- <div class="col-md-4">
            <div class="card" style="width:360px;margin:30px;">
                <a href="{% url 'mainapp:temp_view' n.id %}">
                    <img src="{{n.temp_img.url}}" class="card-img-top" alt="..." >
                </a>
            </div>
       </div> -->
       <div class="col-lg-4 menu-item" style="margin-bottom:70px;">
        <a href="{% url 'mainapp:temp_view' n.id %}" >
          <img src="{{n.temp_img.url}}" class="menu-im img-fluid" alt="" style="width:100%; height:200px; margin-right:20px;">
          <a type="submit" href="{% url 'mainapp:temp_view' n.id %}" class="preview-button btn">
            <i class='fas fa-eye' style="margin-right:7px;"></i>Preview
          </a>
        </a>
      </div>
       {% endfor %}
       {% endif %}
   </div>
</div>

<!--<div class="mx-auto">-->
<!--    {% if normal.paginator.num_pages > 1 %}-->
<!--    <hr>-->
<!--    <div class="text-center">-->
<!--        {% for pg in normal.paginator.page_range %}-->
<!--        <a href="?page={{pg}}" class="btn btn-dark btn-md text-light {% if normal.number == pg %} active {% endif %}">{{pg}}</a>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--    {% endif %}-->
<!--</div>-->


    <footer id="footer" class="footer" style="margin-top:30px;">
        <div class="container">
            <div class="row gy-3">
                <div class="col-lg-3 col-md-6 d-flex">
                    <i class="bi bi-geo-alt icon"></i>
                    <div>
                        <h4>Address</h4>
                        <p>
                          A108 Adam Street <br>
                          New York, NY 535022 - US<br>
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 footer-links d-flex">
                    <i class="bi bi-telephone icon"></i>
                    <div>
                        <h4>Reservations</h4>
                        <p>
                          <strong>Phone:</strong> +1 5589 55488 55<br>
                          <strong>Email:</strong> info@example.com<br>
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 footer-links d-flex">
                    <i class="bi bi-clock icon"></i>
                    <div>
                        <h4>Opening Hours</h4>
                        <p>
                        <strong>Mon-Sat: 11AM</strong> - 23PM<br>
                        Sunday: Closed
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Follow Us</h4>
                    <div class="social-links d-flex">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Foxdale</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">Foxdale</a>
            </div>
        </div>
    </footer>


</body>
</html>

tempbuys/templates/morepremium.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Gallery</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
         <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="static/mainhtml/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="static/mainhtml/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="static/mainhtml/assets/css/main.css" rel="stylesheet">

       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</head>
<body>

<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1><img src="static/mainhtml/assets/img/foxdale/foxdalenavbar.jpg"></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'mainapp:home' %}#home">Home</a></li>
          <li><a href="{% url 'mainapp:home' %}#about">About</a></li>
          <li><a href="{% url 'mainapp:home' %}#normal">Templates</a></li>
          <li><a href="#footer">Contact</a></li>
            <form class="d-flex" role="search" method="get" action="{% url 'mainapp:morepremium' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

        </ul>
      </nav><!-- .navbar -->

      <a class="btn-book-a-table" href="{% url 'login:signin' %}">Login</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header>


  <style>
    .menu-item {
      position: relative;
      overflow: hidden;
    }
  
    .menu-im {
      transition: transform 0.3s ease-in-out;
    }
  
    .menu-item:hover .menu-im,
    .menu-item.touch-active .menu-im {
      transform: scale(1.1);
    }
  
    .preview-button {
      position: absolute;
      bottom: 0;
      right: 0;
      margin: 10px;
      background-color: #ce1212;
      color: white;
      padding: 10px 20px;
      text-decoration: none;
      opacity: 0;
      transition: opacity 0.3s ease-in-out;
      pointer-events: none; /* Make the button not respond to mouse events */
    }
  
    .menu-item:hover .preview-button {
      opacity: 1;
    }
  </style>
  
  <script>
    // Add touch event handling using JavaScript
    document.addEventListener("DOMContentLoaded", function () {
      var menuItems = document.querySelectorAll(".menu-item");
  
      menuItems.forEach(function (menuItem) {
        menuItem.addEventListener("touchstart", function () {
          this.classList.add("touch-active");
        });
  
        menuItem.addEventListener("touchend", function () {
          this.classList.remove("touch-active");
        });
      });
    });
  </script>

<div class="container" style="margin-top:150px;">
   <div class="row">
       {% if query %}
       {% for s in search %}
       <div class="col-lg-4 menu-item" style="margin-bottom:70px;">
        <a href="{% url 'mainapp:temp_view' s.id %}">
          <img src="{{s.temp_img.url}}" class="menu-im img-fluid" alt="" style="width:100%; height:200px; margin-right:20px;">
          <a type="submit" href="{% url 'mainapp:temp_view' s.id %}" class="preview-button btn">
            <i class='fas fa-eye' style="margin-right:7px;"></i>Preview
          </a>
        </a>
      </div>
       {% endfor %}
       {% else %}
       {% for p in premium %}
       <div class="col-lg-4 menu-item" style="margin-bottom:70px;">
        <a href="{% url 'mainapp:temp_view' p.id %}">
          <img src="{{p.temp_img.url}}" class="menu-im img-fluid" alt="" style="width:100%; height:200px; margin-right:20px;">
          <a type="submit" href="{% url 'mainapp:temp_view' p.id %}" class="preview-button btn">
            <i class='fas fa-eye' style="margin-right:7px;"></i>Preview
          </a>
        </a>
      </div>
       {% endfor %}
       {% endif %}
   </div>
</div>

<div class="mx-auto">
    {% if premium.paginator.num_pages > 1 %}
    <hr>
    <div class="text-center">
        {% for pg in premium.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-dark btn-md text-light {% if premium.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>

  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022 - US<br>
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Reservations</h4>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 11AM</strong> - 23PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Foxdale</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://bootstrapmade.com/">Foxdale</a>
      </div>
    </div>

  </footer>



</body>
</html>

tempbuys/templates/purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Purchase Confirmation</title>
</head>
<body>
    <h1>Purchase Confirmation</h1>
    <p>You have successfully purchased the template card with ID {{ template_card.id }}.</p>
    <!-- Add more purchase details or actions here -->
</body>
</html>